//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPLANT
    {
        public EPLANT()
        {
            this.DOC_LIBRARY = new HashSet<DOC_LIBRARY>();
            this.S_USER_GENERAL = new HashSet<S_USER_GENERAL>();
            this.TEAM_MEMBER = new HashSet<TEAM_MEMBER>();
            this.VENDOR = new HashSet<VENDOR>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ECOMPANY_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string ECODE { get; set; }
        public Nullable<long> EID { get; set; }
        public Nullable<System.DateTime> EDATE_TIME { get; set; }
        public string ECOPY { get; set; }
        public string GL_PLUG_VALUE { get; set; }
        public string COMPANY { get; set; }
        public string SMTP_SERVER { get; set; }
        public Nullable<long> LAST_PS { get; set; }
        public Nullable<long> LAST_AR { get; set; }
        public Nullable<long> LAST_PO { get; set; }
        public Nullable<long> LAST_SO { get; set; }
        public Nullable<long> LAST_RMA { get; set; }
        public Nullable<long> LAST_RFQ { get; set; }
        public Nullable<long> LAST_PO_REC { get; set; }
        public Nullable<long> LAST_PHYS { get; set; }
        public string TAGINV_STATE { get; set; }
        public Nullable<System.DateTime> TAGINV_STATE_DATE { get; set; }
        public string SUFFIX { get; set; }
        public string COSTING_SYSTEM { get; set; }
        public Nullable<long> EIN_ID { get; set; }
        public string NATIVE_CURR { get; set; }
        public Nullable<long> LAST_BOL { get; set; }
        public string TAGINV_METHOD { get; set; }
        public string FAX_POLL_PATH { get; set; }
        public Nullable<int> FAX_POLL_INTERVAL { get; set; }
        public Nullable<long> ARCUSTO_ID_INTERCOMP { get; set; }
        public Nullable<long> MAINFORM_COLOR { get; set; }
        public string SEPARATE_FISCAL_YEAR { get; set; }
        public string METRIC_UOM { get; set; }
        public string INACTIVE { get; set; }
        public string USE_EPLANT_PK_TKT_PARAMS { get; set; }
        public string PK_TKT_ORDERS_BASED { get; set; }
        public string PK_TKT_SO_MODE_PKLIST_BY_DIV { get; set; }
        public string PK_TKT_PICK_BY_CUSTOMER { get; set; }
        public string PK_TKT_ONE_PER_CUSTOMER { get; set; }
        public string PK_TKT_SHOW_ALL { get; set; }
        public string PK_TKT_KEEP_REL_SEPARATE { get; set; }
        public string PK_TKT_USE_SHIP_DEFAULT { get; set; }
        public string PK_TKT_CONV_USE_SYSDATE { get; set; }
        public string RF_SERIALIZED_ROUTING { get; set; }
        public string PK_TKT_SORT_NULL_RAN_TOP { get; set; }
        public string PK_TKT_ENABLE_VOLUME_CALC { get; set; }
        public string CALC_SHIP_DAY_START_VALID { get; set; }
        public string PK_TKT_DO_NOT_PRNT_PS_ON_CONV { get; set; }
        public string PK_TKT_DO_NOT_PRNT_BOL_ON_CONV { get; set; }
        public string PS_EVAL_OVERSHIP { get; set; }
        public string PS_VERIFY_INVENTORY { get; set; }
        public string PK_TKT_SO_SYNC_AFTER_EDI { get; set; }
        public string PK_TKT_ASSIGN_ASN_ON_PRINT_LBL { get; set; }
        public string PK_TKT_LABEL_MUST_BE_DISPO { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string PK_TKT_STAGE_BY_PALLET { get; set; }
        public string RFQ_XLS_PATH { get; set; }
        public string TAGINV_REQUIRE_ALL_COUNTED { get; set; }
        public string PK_TKT_HARD_ALLOC_ON_PICK { get; set; }
        public Nullable<long> LAST_AP { get; set; }
        public string IIS_SERVER_URL { get; set; }
        public Nullable<short> IIS_PORT { get; set; }
        public string PCMON_LOG_INSTANCE { get; set; }
        public string AUTHENTICATE_EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public string PK_TKT_PKLIST_BY_SO_DIV { get; set; }
        public byte[] APP_ICON { get; set; }
        public Nullable<bool> ENABLE_VEND_NUM_GEN { get; set; }
        public Nullable<bool> ENABLE_CUST_NUM_GEN { get; set; }
        public string NOT_VISIBLE { get; set; }
        public string EMAIL_PROFILE_NAME { get; set; }
        public string EMAIL_BCC { get; set; }
        public Nullable<long> SMTP_PORT { get; set; }
        public string RELIEVE_TO_PARENT_METHOD { get; set; }
        public string EMAIL_SECURE { get; set; }
        public string TZNAME { get; set; }
        public string TZABBREV { get; set; }
        public Nullable<long> LAST_AF { get; set; }
    
        public virtual ICollection<DOC_LIBRARY> DOC_LIBRARY { get; set; }
        public virtual ICollection<S_USER_GENERAL> S_USER_GENERAL { get; set; }
        public virtual ICollection<TEAM_MEMBER> TEAM_MEMBER { get; set; }
        public virtual ICollection<VENDOR> VENDOR { get; set; }
    }
}
