//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_USER
    {
        public long ID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<long> PR_EMP_ID { get; set; }
        public Nullable<long> VENDOR_ID { get; set; }
        public Nullable<long> VENDOR_CONTACT_ID { get; set; }
        public string EXP_APPROVER { get; set; }
        public Nullable<decimal> MILEAGE_RATE { get; set; }
        public string NO_APPROVER_EDIT { get; set; }
        public string INACTIVE { get; set; }
        public string WORKFLOW { get; set; }
    
        public virtual PR_EMP PR_EMP { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
