//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IQMS_Entities : DbContext
    {
        public IQMS_Entities()
            : base("name=IQMS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOC_LIBRARY> DOC_LIBRARY { get; set; }
        public virtual DbSet<EPLANT> EPLANT { get; set; }
        public virtual DbSet<EXP_USER> EXP_USER { get; set; }
        public virtual DbSet<PR_EMP> PR_EMP { get; set; }
        public virtual DbSet<S_USER_GENERAL> S_USER_GENERAL { get; set; }
        public virtual DbSet<TEAM_MEMBER> TEAM_MEMBER { get; set; }
        public virtual DbSet<VENDOR> VENDOR { get; set; }
        public virtual DbSet<REMIT_TO> REMIT_TO { get; set; }
        public virtual DbSet<DOC_TEAM> DOC_TEAM { get; set; }
    }
}
