//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_EMP
    {
        public PR_EMP()
        {
            this.EXP_USER = new HashSet<EXP_USER>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PR_DEPARTMENT_ID { get; set; }
        public Nullable<long> PR_PAYTYPE_ID { get; set; }
        public Nullable<long> PR_PAYGROUP_ID { get; set; }
        public string EMPNO { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SSNMBR { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIP { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string CITY { get; set; }
        public Nullable<decimal> CHARGE_RATE { get; set; }
        public string STATUS_CODE { get; set; }
        public Nullable<System.DateTime> DATE_HIRED { get; set; }
        public Nullable<System.DateTime> TERMINATION_DATE { get; set; }
        public Nullable<System.DateTime> LAST_REVIEW_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_REVIEW_DATE { get; set; }
        public string RACE { get; set; }
        public string SEX { get; set; }
        public string BASIS { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string CITIZEN { get; set; }
        public string MARRIED_STATUS { get; set; }
        public string EIC_MARRIED_STATUS { get; set; }
        public Nullable<decimal> EIC { get; set; }
        public string LABOR_INDICATOR { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<long> HANDICAP { get; set; }
        public string COMMENT1 { get; set; }
        public Nullable<long> PLUGIN_ENTITY_ID { get; set; }
        public string CONTACT { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string JOB_TITLE { get; set; }
        public string CUSER1 { get; set; }
        public string CUSER2 { get; set; }
        public string CUSER3 { get; set; }
        public string CUSER4 { get; set; }
        public string CUSER5 { get; set; }
        public string CUSER6 { get; set; }
        public Nullable<decimal> NUSER1 { get; set; }
        public Nullable<decimal> NUSER2 { get; set; }
        public Nullable<decimal> NUSER3 { get; set; }
        public Nullable<decimal> NUSER4 { get; set; }
        public Nullable<decimal> NUSER5 { get; set; }
        public Nullable<System.DateTime> RESET_BENEFITS_DATE { get; set; }
        public Nullable<long> EMP_STATUS_ID { get; set; }
        public Nullable<long> ELEMENTS_ID { get; set; }
        public Nullable<long> TA_SETTINGS_ID { get; set; }
        public Nullable<long> TA_SHIFT_ID { get; set; }
        public string TURN_OFF_DD { get; set; }
        public Nullable<long> SNDOP_ID { get; set; }
        public Nullable<System.DateTime> RESIDENT_VISA_EXPR { get; set; }
        public Nullable<long> OT1_PR_PAYTYPE_ID { get; set; }
        public Nullable<long> OT2_PR_PAYTYPE_ID { get; set; }
        public Nullable<long> OT3_PR_PAYTYPE_ID { get; set; }
        public Nullable<long> HR_JOB_DESCRIP_ID { get; set; }
        public string BADGENO { get; set; }
        public string PK_HIDE { get; set; }
        public string WEB_USERID { get; set; }
        public Nullable<long> EMP_LEVEL_ID { get; set; }
        public string SUTA_TAX_STATE { get; set; }
        public string SWT_STATE { get; set; }
        public string EMAIL { get; set; }
        public string SUPERVISOR { get; set; }
        public Nullable<long> SUPERVISOR_ID { get; set; }
        public string HR_MARRIED_STATUS { get; set; }
        public Nullable<long> PR_HOLIDAY_PAYTYPE_ID { get; set; }
        public Nullable<System.DateTime> LAST_CALC_DATE { get; set; }
        public Nullable<long> AUTO_PR_PAYTYPE_ID { get; set; }
        public string MOBILE { get; set; }
        public string PAGER { get; set; }
        public string VETERAN_STATUS { get; set; }
        public Nullable<long> MFGCELL_ID { get; set; }
        public string EMP_PROV_CD { get; set; }
        public string SUFFIX { get; set; }
        public string EW2 { get; set; }
        public Nullable<long> CURRENCY_LANGUAGE_ID { get; set; }
        public Nullable<long> CURRENCY_ID { get; set; }
        public string DISTLIST { get; set; }
        public string DISABLED { get; set; }
        public string QUAL_DIS_VET { get; set; }
        public string ARM_FORC_VET { get; set; }
        public string OTHER_PROT_VET { get; set; }
        public string NEW_SEP_VET { get; set; }
        public Nullable<System.DateTime> SEPARATION_DATE { get; set; }
    
        public virtual ICollection<EXP_USER> EXP_USER { get; set; }
    }
}
