//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_USER_GENERAL
    {
        public string USER_NAME { get; set; }
        public Nullable<int> AUTO_SHUT_TIME { get; set; }
        public Nullable<long> EPLANT_ID { get; set; }
        public Nullable<long> PO_LIMIT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> RMA_LIMIT { get; set; }
        public Nullable<long> PR_EMP_ID { get; set; }
        public string PO_APPROVER { get; set; }
        public Nullable<long> PO_CAP_LIMIT { get; set; }
        public Nullable<long> PO_EXP_LIMIT { get; set; }
        public string WEB_MASTER { get; set; }
        public string PO_CANT_INCR_COST { get; set; }
        public Nullable<bool> AUTO_SHUT_ACTION_CODE { get; set; }
        public string NOTIFICATION_PRINTER { get; set; }
        public string DONT_CHANGE_POAP { get; set; }
        public string PO_BUYER { get; set; }
        public string PO_CAN_DENY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string AUTO_SHUT_SHOPDATA { get; set; }
        public Nullable<byte> LANGUAGE_CODE { get; set; }
        public string FORCE_PASSWORD_CHANGE { get; set; }
        public string IS_NEW_USER { get; set; }
        public Nullable<System.DateTime> NEW_USER_TIMESTAMP { get; set; }
        public string SEC_PREVENT_SAME_USER_LOGIN { get; set; }
        public string SEC_ALLOW_NON_DBA_SEC_INS { get; set; }
        public Nullable<decimal> INV_ADJ_LIMIT { get; set; }
        public string IS_MOBILE_USER { get; set; }
        public Nullable<decimal> RECEIPT_TOLERANCE { get; set; }
        public Nullable<decimal> AP_TOLERANCE { get; set; }
        public string EMAIL_SIGNATURE { get; set; }
        public string SHIP_MANAGER_WARNING { get; set; }
        public string CUSER1 { get; set; }
        public byte[] SP_PROFILE { get; set; }
        public byte[] SP_WORKSPACE { get; set; }
        public string EXCLUDE_CUSTOMERS { get; set; }
        public string EXCLUDE_VENDORS { get; set; }
    
        public virtual EPLANT EPLANT { get; set; }
    }
}
