//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iq_add_user.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM_MEMBER
    {
        public TEAM_MEMBER()
        {
            this.DOC_TEAM = new HashSet<DOC_TEAM>();
        }
    
        public long ID { get; set; }
        public string USERID { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string EMAIL { get; set; }
        public string WORK_PATH { get; set; }
        public string USED_DOC { get; set; }
        public string USED_CAR { get; set; }
        public string USED_APQP { get; set; }
        public string USED_ECO { get; set; }
        public string USED_PPAP { get; set; }
        public Nullable<long> EPLANT_ID { get; set; }
        public string USED_CAPA { get; set; }
        public string USED_DEV { get; set; }
        public string USED_PROD_PQ { get; set; }
        public string USED_PROC_PQ { get; set; }
        public string USED_MRB { get; set; }
        public string USED_PO { get; set; }
        public string USED_CRM { get; set; }
        public string USED_AUDIT { get; set; }
        public string TYPE { get; set; }
        public string OUT_OF_OFFICE { get; set; }
    
        public virtual EPLANT EPLANT { get; set; }
        public virtual ICollection<DOC_TEAM> DOC_TEAM { get; set; }
    }
}
